spring:
  application:
    name: apiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**
        - id: medication-service
          uri: http://medicine-service:8080
          predicates:
            - Path=/medicine/**
        - id: reminder-service
          uri: http://reminder-service:8084
          predicates:
            - Path=/reminder/**
        - id: pharmacy-service
          uri: http://pharmacy-service:8086
          predicates:
            - Path=/pharmacy/**

server:
  port: 8083

jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast64CharactersLongForHS512Algorithm
