spring:
  application:
    name: apiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: medication-service
          uri: http://localhost:8080
          predicates:
            - Path=/medicine/**
        - id: reminder-service
          uri: http://localhost:8084
          predicates:
            - Path=/reminder/**
        - id: pharmacy-service
          uri: http://localhost:8086
          predicates:
            - Path=/pharmacy/**
        - id: chatbot-service
          uri: http://localhost:8087
          predicates:
            - Path=/chatbot/**

server:
  port: 8083

jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast64CharactersLongForHS512Algorithm
